### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by 0n** [Armchair-Software/vectorstorm#1]
Hey I know it's not the right place or anything but I don't really have another way to contact you @slowriot 

I would like to talk to you about your Minecraft server MinecraftOnline

What's your discord so I can add you?

**Comment by slowriot** [comment]
Please send any enquires re. MinecraftOnline to admins[@]minecraftonline.com.

**Comment by 0n** [comment]
@slowriot I did before I even made this post, it's been two weeks since I sent an email and I haven't heard back
